//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int branchid { get; set; }
        public string bcity { get; set; }
        public string Location { get; set; }
        public Nullable<long> bphonenum { get; set; }
        public byte[] bimage { get; set; }
        public string Rname { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
